### ISSUE TITLE
Upgraded Cockroachdb and Schema

### ISSUE THREAD

**Issue by fire** [cloudtrust/keycloak-cockroach#2]
Will https://www.cockroachlabs.com/docs/v20.1/alter-primary-key.html make this repository unnecessary?

**Comment by Cellebyte** [comment]
I tested keycloak 10.0.1 against the new cockroach and it was creating the liquibase lock table but got stuck on it. I don't have debugged further but the keycloak run into some query timeouts. So I don't think that it currently works out of the box.
